
version: '3'

services:
  boilerplate_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5457:5432"

  boilerplate:
    image: boilerplate
    container_name: boilerplate
    build: .
    entrypoint: ./entrypoint.sh
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - boilerplate_database
      

volumes:
  pgdata: